
SIDE_SIZE = 8
RED = "X "
WHITE = "O "
EMPTY = ". "
LEGAL = "L "
MAX = RED
MIN = WHITE
TIE = 0
NUMBER_OF_INITIAL_DISKS = 4

# Constants for graphics
BACKGROUND_COLOR = "light blue"
OUTLINE_COLOR = "black"
FILL_COLOR_PLAYER1 = "red"
FILL_COLOR_PLAYER2 = "white"
FILL_COLOR_LEGAL = BACKGROUND_COLOR
OUTLINE_COLOR_LEGAL = "green"
# Constants for directions
UP = -1
DOWN = 1
LEFT = -1
RIGHT = 1
STAY = 0


#actions
ADD = 1
SKIP = 0

MIDDLE = SIDE_SIZE // 2


CELL_SIZE = 100
EXTRA = CELL_SIZE
PADDING = CELL_SIZE * 0.1
LEGAL_PADDING = PADDING * 2
DISPLAY_ALL_ACTIONS = 0
METHODICAL = 1
H = 'H'